"""Initial migration.

Revision ID: ad312106137a
Revises: 
Create Date: 2024-06-11 14:19:38.532531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad312106137a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nPerCode', sa.Integer(), nullable=False),
    sa.Column('cPerLastname', sa.String(length=255), nullable=False),
    sa.Column('cPerName', sa.String(length=255), nullable=False),
    sa.Column('cPerAddress', sa.String(length=255), nullable=True),
    sa.Column('cPerDateBorn', sa.DateTime(), nullable=True),
    sa.Column('nPerYears', sa.Integer(), nullable=True),
    sa.Column('nPerSalary', sa.Numeric(), nullable=True),
    sa.Column('cPerRnd', sa.String(length=255), nullable=True),
    sa.Column('cPerState', sa.String(length=255), nullable=True),
    sa.Column('remember_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cPerSexo', sa.String(length=15), nullable=True),
    sa.Column('cPerEmail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persona')
    # ### end Alembic commands ###
